name: matricare_444
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_database: ^12.1.0
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4

  shared_preferences: ^2.2.2

  # Notifications / Permissions
  flutter_local_notifications: ^19.5.0
  flutter_background_service: ^5.0.0
  permission_handler: ^12.0.1

  # UI & UX
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.3.2
  syncfusion_flutter_gauges: ^31.2.12
  smooth_page_indicator: ^1.1.0

  # Navigation
  go_router: ^17.0.0
  google_maps_flutter: ^2.5.0
  # Sensors
  sensors_plus: ^7.0.0
  geolocator: ^14.0.2
  flutter_tts: ^4.2.3

  # Exporting
  pdf: ^3.11.3
  csv: ^6.0.0
  open_filex: ^4.4.0
  path_provider: ^2.1.2
  share_plus: ^12.0.1
  url_launcher: ^6.3.0
  
  fl_chart: ^0.68.0

  # Media
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # AI / Chat
  http: ^1.2.1
  googleapis_auth: ^2.0.0

  # Google Login
  google_sign_in: ^7.2.0

  # Animation
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.2.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true   # ðŸ”¥ this ENABLES gen-l10n

  assets:
    - assets/
    - lib/assets/images/logo_2.jpg
    - assets/lang/   # optional if you're using JSON for some reason

l10n:
  arb-dir: assets/lang
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
    # Localizations
#  l10n:
#    arb-dir: lib/l10n
#    template-arb-file: app_en.arb
#    output-localization-file: app_localizations.dart